services:
  postgresql:
    image: postgres:17.10-alpine
    container_name: leaf-postgresql
    restart: unless-stopped
    ports: [ "5432:5432" ]
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - /docker/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_URL}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  leaf-rbac:
    depends_on:
      postgresql:
        condition: service_healthy